### ISSUE TITLE
GLOBAL #TODO AFTER REVIEW

### ISSUE THREAD

**Issue by powerswing** [ztsv-av/spellbook#1]
# FIX YOUR REPO FIRST

- [x] SAVE LOCAL FILES FIRST (f.e. copy all files into a folder on Desktop)
- [x] Create a new repo
- [x] Move only the necessary files (folders and scripts excluding `.git` and `.gitignore`) and push directly (preferably in one commit called 'mv from old repo')
- [x] Check that the files you pushed are of the latest version
- [x] Copy and paste open issues to new repo (including this issue with content below starting from [TODO After Big Review](#todo-after-big-review))
- [x] Archive (not delete) this repo

## TODO After Big Review

Each subheader is a subissue itself so take care of each of those and tick the boxes

- [x] Remove Preprocess Steps from `prepareTrainDataset.py`
- [x] Template Description for Bounding Boxes `.csv`
- [x] Fix Callable Parameters and Add Save Weights Callback in `train.py`
- [x] Update Projects' `README.md`
- [x] Fill Function Descriptions
- [x] Finish Repo's `README.md`

### Remove Preprocess Steps from `prepareTrainDataset.py`

Each competition folder must have two directories with raw and preprocessed data (so we don't have to preprocess the same data for each new model with `prepareTrainDataset.py`)

The preprocess of the raw data and saving of the preprocessed data must be done in a separate script `preprocessData.py` with the following logic:

- it has a wrapper for preprocess functions imported from `preprocessFunctions.py` (including normalization of boxes)
- this wrapper takes on three parameters
  - source path (raw data) *probably a global variable*
  - target path (location  to save preprocessed data) *probably a global variable*
  - dictionary of preprocessing functions

### Template Description for Bounding Boxes `.csv`

Add a template description on how proper `.csv` for bounding boxes should look like

### Fix Callable Parameters and Add Save Weights Callback in `train.py`

Fix callable parameters in `train.py` for all functions inside the script, and add save weights callback for classification part

### Update Projects' `README.md`

Since we don't upload project data - add info that data are taken from Kaggle comps using hyperlinks

### Fill Function Descriptions

Add descriptions (adhering to template) to functions touching scripts in the following order:

- `magic.py`
- `prepareTrainDataset.py`
- `prepareTestDataset.py`
- `preprocessData.py`
- `preprocessFunctions.py`
- `models.py`
- `train.py`
- free order afterwards (excluding `generatorInstance.py` since it's deprecated)

### Finish Repo's `README.md`'s

Self-explanatory

**Comment by powerswing** [comment]
By the way, the file list in the main `README.md` should look better in a table like so

File|Description
-|-
`callbacks.py`|blah-blah
`magic.py`|blah-blah
`train.py`|blah-blah

**Comment by ztsv-av** [comment]
all tasks done. need to do a full review again.
